language: ruby
rvm:
  - 1.9.3
  - 1.8.7
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "DISPLAY=:99.0 bundle exec rake test_app"

script: "DISPLAY=:99.0 bundle exec rspec spec"
